on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.USERNAME }}
          SSH_HOSTNAME: ${{ secrets.HOSTNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USERNAME@$SSH_HOSTNAME << 'EOF'
            
            cd arboratorgrew_parser
            git pull origin main
            
            cd frontend
            npm install
            npm run build

            cd ../backend
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart parser.service
          EOF
