on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts

      - env:
        ACTIONS_STEP_DEBUG: true

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }} << 'EOF'
            
            cd arboratorgrew_parser
            git pull origin main
            
            cd frontend
            npm install
            npm run build

            cd ../backend
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart parser.service
          EOF
